version: '3.8'

services:
  app:
    image: dunglas/frankenphp:latest
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/app
    environment:
      - FRANKENPHP_WORKER_MODE=true
      - APP_ENV=local
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=true
    depends_on:
      - db
    networks:
      - laravel-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketing
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-network

volumes:
  db-data:

networks:
  laravel-network:
    driver: bridge